# Generated by Django 4.2.8 on 2025-05-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blogcategory_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='about_text',
            field=models.TextField(blank=True, help_text='Text for the about section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cookie_url',
            field=models.URLField(blank=True, help_text='URL to the cookie policy page'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_button_text',
            field=models.CharField(blank=True, help_text='Text for the CTA button', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_image',
            field=models.ImageField(blank=True, help_text='Image for the CTA section', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_text',
            field=models.TextField(blank=True, help_text='Text for the CTA section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='cta_title',
            field=models.CharField(blank=True, help_text='Title for the CTA section', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='footer_tagline',
            field=models.TextField(blank=True, help_text='Tagline to display in the footer'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='guarantee_icon',
            field=models.CharField(blank=True, help_text='Font Awesome icon class for the guarantee icon', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='guarantee_text',
            field=models.CharField(blank=True, help_text='Text for the guarantee badge', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='guarantee_title',
            field=models.CharField(blank=True, help_text='Title for the guarantee badge', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission_text',
            field=models.TextField(blank=True, help_text='Mission statement text'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='newsletter_text',
            field=models.TextField(blank=True, help_text='Text for the newsletter signup section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_url',
            field=models.URLField(blank=True, help_text='URL to the privacy policy page'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='quote_text',
            field=models.TextField(blank=True, help_text='Quote text for the about section'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='site_name_suffix',
            field=models.CharField(blank=True, help_text='Optional suffix for the site name that will be styled differently', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='students_count',
            field=models.CharField(blank=True, help_text='Number of students/members to display', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_url',
            field=models.URLField(blank=True, help_text='URL to the terms of service page'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='years_experience',
            field=models.CharField(blank=True, help_text='Years of experience to display', max_length=50),
        ),
    ]
